all:
  children:
    sdwan_edges:
      hosts:
        site-east:
          ansible_host: 172.174.45.166
          ansible_user: azureuser
        site-west:
          ansible_host: 13.64.114.23
          ansible_user: azureuser
